version: '3'

services:
  auth-client:
    image: node:18.2.0-alpine3.15 # Use Node.js version 18
    working_dir: /app
    ports:
      - "5173
       :3000"
    volumes:
      - ./auth-client:/app
    environment:
      - NODE_ENV=development
    command: >
      sh -c "rm -rf node_modules package-lock.json && npm install && npm run dev"

  auth-server:
    image: node:18.2.0-alpine3.15 # Use Node.js version 16.20.1
    working_dir: /app
    ports:
      - "8001:8000"
    volumes:
      - ./auth-server:/app
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb+srv://jaybhandari2404:LOhWsmZSlv1WbZrd@cluster0.nj8fje8.mongodb.net/Auth-Yt?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - auth-client
    command: >
      sh -c "rm -rf node_modules package-lock.json && npm install && npm start"
